name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"] # Adjust the branch name as needed

jobs:
  build:
    name: Build app from source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify Node.js version 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build:ncc
        run: npm run build:ncc

      - name: Copy dist directory
        run: cp -r dist $GITHUB_WORKSPACE/dist  # Copy dist to workspace

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: $GITHUB_WORKSPACE/dist  # Adjusted to use the dist directory
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-socket-gps:latest
