name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # Adjust the branch name as needed

jobs:
  build:
    name: Build binary from source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Cache NCC binaries
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-ncc-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ncc-

      - name: Install NCC
        run: npm install -g @vercel/ncc

      - name: Build binary using NCC
        run: npm run build:ncc

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile  # Ensure this path points to your Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-socket-gps:latest
