name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"] # Adjust the branch name as needed

jobs:
  build:
    name: Build app from source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify Node.js version 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install @vercel/ncc
        run: npm install -g @vercel/ncc

      - name: Run build:ncc
        run: npm run build:ncc

      - name: Check if dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi

      - name: Upload artifact dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: List Directories
        run: ls -d */

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile  # Ensure this path points to your Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-socket-gps:latest
